### ISSUE TITLE
Celery error psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

### ISSUE THREAD

**Issue by CarlesLopezMagem** [saleor/saleor-platform#201]
Hi,
I get this issue when I run `docker-compose up worker`:
```
worker_1               | 2022-10-28 08:55:16,525 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:17,030 WARNING py.warnings /usr/local/lib/python3.9/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
worker_1               | absolutely not recommended!
worker_1               | 
worker_1               | Please specify a different user using the --uid option.
worker_1               | 
worker_1               | User information: uid=0 euid=0 gid=0 egid=0
worker_1               | 
worker_1               |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker_1               |  [PID:1:MainThread]
worker_1               |  
worker_1               |  -------------- celery@9468a84fdfae v5.2.7 (dawn-chorus)
worker_1               | --- ***** ----- 
worker_1               | -- ******* ---- Linux-5.10.76-linuxkit-x86_64-with-glibc2.31 2022-10-28 08:55:17
worker_1               | - *** --- * --- 
worker_1               | - ** ---------- [config]
worker_1               | - ** ---------- .> app:         saleor:0x7f5c1d34f280
worker_1               | - ** ---------- .> transport:   redis://redis:6379/1
worker_1               | - ** ---------- .> results:     disabled://
worker_1               | - *** --- * --- .> concurrency: 2 (prefork)
worker_1               | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_1               | --- ***** ----- 
worker_1               |  -------------- [queues]
worker_1               |                 .> celery           exchange=celery(direct) key=celery
worker_1               |                 
worker_1               | 
worker_1               | [tasks]
worker_1               |   . export-gift-cards
worker_1               |   . export-products
worker_1               |   . saleor.app.tasks.install_app_task
worker_1               |   . saleor.attribute.tasks.update_associated_products_search_vector
worker_1               |   . saleor.checkout.tasks.delete_expired_checkouts
worker_1               |   . saleor.core.analytics.ga_report
worker_1               |   . saleor.core.search_tasks.set_order_search_document_values
worker_1               |   . saleor.core.search_tasks.set_product_search_document_values
worker_1               |   . saleor.core.search_tasks.set_user_search_document_values
worker_1               |   . saleor.core.tasks.delete_event_payloads_task
worker_1               |   . saleor.core.tasks.delete_files_from_storage_task
worker_1               |   . saleor.core.tasks.delete_from_storage_task
worker_1               |   . saleor.core.tasks.delete_product_media_task
worker_1               |   . saleor.csv.tasks.delete_old_export_files
worker_1               |   . saleor.discount.tasks.send_sale_toggle_notifications
worker_1               |   . saleor.giftcard.tasks.deactivate_expired_cards_task
worker_1               |   . saleor.order.tasks.recalculate_orders_task
worker_1               |   . saleor.order.tasks.send_order_updated
worker_1               |   . saleor.plugins.admin_email.tasks.send_email_with_link_to_download_file_task
worker_1               |   . saleor.plugins.admin_email.tasks.send_export_failed_email_task
worker_1               |   . saleor.plugins.admin_email.tasks.send_set_staff_password_email_task
worker_1               |   . saleor.plugins.admin_email.tasks.send_staff_order_confirmation_email_task
worker_1               |   . saleor.plugins.admin_email.tasks.send_staff_password_reset_email_task
worker_1               |   . saleor.plugins.avatax.tasks.api_post_request_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_account_confirmation_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_account_delete_confirmation_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_email_with_dynamic_template_id
worker_1               |   . saleor.plugins.sendgrid.tasks.send_fulfillment_confirmation_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_fulfillment_update_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_gift_card_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_invoice_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_order_canceled_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_order_confirmation_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_order_confirmed_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_order_refund_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_password_reset_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_payment_confirmation_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_request_email_change_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_set_user_password_email_task
worker_1               |   . saleor.plugins.sendgrid.tasks.send_user_change_email_notification_task
worker_1               |   . saleor.plugins.user_email.tasks.send_account_confirmation_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_account_delete_confirmation_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_fulfillment_confirmation_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_fulfillment_update_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_gift_card_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_invoice_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_order_canceled_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_order_confirmation_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_order_confirmed_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_order_refund_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_password_reset_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_payment_confirmation_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_request_email_change_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_set_user_password_email_task
worker_1               |   . saleor.plugins.user_email.tasks.send_user_change_email_notification_task
worker_1               |   . saleor.plugins.webhook.tasks.observability_reporter_task
worker_1               |   . saleor.plugins.webhook.tasks.observability_send_events
worker_1               |   . saleor.plugins.webhook.tasks.send_webhook_request_async
worker_1               |   . saleor.product.tasks.deactivate_preorder_for_variants_task
worker_1               |   . saleor.product.tasks.update_product_discounted_price_task
worker_1               |   . saleor.product.tasks.update_products_discounted_prices_of_catalogues_task
worker_1               |   . saleor.product.tasks.update_products_discounted_prices_of_discount_task
worker_1               |   . saleor.product.tasks.update_products_discounted_prices_task
worker_1               |   . saleor.product.tasks.update_products_search_vector_task
worker_1               |   . saleor.product.tasks.update_variants_names
worker_1               |   . saleor.shipping.tasks.drop_invalid_shipping_methods_relations_for_given_channels
worker_1               |   . saleor.warehouse.tasks.delete_empty_allocations_task
worker_1               |   . saleor.warehouse.tasks.delete_expired_reservations_task
worker_1               |   . saleor.warehouse.tasks.update_stocks_quantity_allocated_task
worker_1               | 
worker_1               | 2022-10-28 08:55:17,849 INFO celery.worker.consumer.connection Connected to redis://redis:6379/1 [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:17,854 INFO celery.worker.consumer.mingle mingle: searching for neighbors [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:18,871 INFO celery.worker.consumer.mingle mingle: all alone [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:18,899 WARNING py.warnings /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
worker_1               |             leak, never use this setting in production environments!
worker_1               |   warnings.warn('''Using settings.DEBUG leads to a memory
worker_1               |  [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:18,899 INFO celery.apps.worker celery@9468a84fdfae ready. [PID:1:MainThread]
worker_1               | 2022-10-28 08:55:19,031 INFO celery.beat beat: Starting... [PID:24:MainThread]
worker_1               | Process Beat:
worker_1               | Traceback (most recent call last):
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
worker_1               |     self.connect()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
worker_1               |     self.connection = self.get_new_connection(conn_params)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
worker_1               |     connection = Database.connect(**conn_params)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
worker_1               |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
worker_1               | psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known
worker_1               | 
worker_1               | 
worker_1               | The above exception was the direct cause of the following exception:
worker_1               | 
worker_1               | Traceback (most recent call last):
worker_1               |   File "/usr/local/lib/python3.9/site-packages/billiard/process.py", line 327, in _bootstrap
worker_1               |     self.run()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 720, in run
worker_1               |     self.service.start(embedded_process=True)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 645, in start
worker_1               |     interval = self.scheduler.tick()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 343, in tick
worker_1               |     self.populate_heap()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 317, in populate_heap
worker_1               |     is_due, next_call_delay = entry.is_due()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 160, in is_due
worker_1               |     return self.schedule.is_due(self.last_run_at)
worker_1               |   File "/app/saleor/core/schedules.py", line 90, in is_due
worker_1               |     if not upcoming_start_dates and not upcoming_end_dates:
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 284, in __bool__
worker_1               |     self._fetch_all()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
worker_1               |     self._result_cache = list(self._iterable_class(self))
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
worker_1               |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
worker_1               |     cursor = self.connection.cursor()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
worker_1               |     return self._cursor()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
worker_1               |     self.ensure_connection()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
worker_1               |     self.connect()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
worker_1               |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
worker_1               |     self.connect()
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
worker_1               |     self.connection = self.get_new_connection(conn_params)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
worker_1               |     return func(*args, **kwargs)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
worker_1               |     connection = Database.connect(**conn_params)
worker_1               |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
worker_1               |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
worker_1               | django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
worker_1               | 
```

**Comment by l4b4r4b4b4** [comment]
Same here.
