### ISSUE TITLE
Build with podman-compose

### ISSUE THREAD

**Issue by reinow** [saleor/saleor-platform#204]
I cloned the saleor-platform repository:

$ git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3

then

$ cd saleor-platform
$ podman-compose build

...
...
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1354, in compose_build
    build_one(compose, args, cnt)
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1327, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in .

$ podman images
REPOSITORY                           TAG         IMAGE ID      CREATED        SIZE
localhost/saleor-platform_api        latest      b4e2daab11c1  2 minutes ago  952 MB
localhost/saleor-platform_worker     latest      b4e2daab11c1  2 minutes ago  952 MB
none                               none      18eafb24be2a  4 minutes ago  1.75 GB
localhost/saleor-platform_dashboard  latest      c5cf58b6c424  7 minutes ago  2.57 GB
...
...

Anyone with the same problem? Any hints how to solve this issue?

**Comment by lacosteque** [comment]
I have the same problem, and could not solve it
