### ISSUE TITLE
docker-compose build on master dont work, got some python package error

### ISSUE THREAD

**Issue by jhsenjaliya** [saleor/saleor-platform#227]
steps to reproduce: ( followed the readme to run the saleor platform locally with docker)

```git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build```

Note: the shared folder was added and docker was given 8GB of memory. This is on mac M1, OS: Ventura

Error: 

```Collecting measurement==3.2.0
#0 30.17   Downloading measurement-3.2.0.tar.gz (12 kB)
#0 30.18   Preparing metadata (setup.py): started
#0 35.30   Preparing metadata (setup.py): finished with status 'error'
#0 35.30   error: subprocess-exited-with-error
#0 35.30
#0 35.30   × python setup.py egg_info did not run successfully.
#0 35.30   │ exit code: 1
#0 35.30   ╰─> [14 lines of output]
#0 35.30       Traceback (most recent call last):
#0 35.30         File "<string>", line 2, in <module>
#0 35.30         File "<pip-setuptools-caller>", line 34, in <module>
#0 35.30         File "/tmp/pip-install-y1ihcgko/measurement_bfb6e0bbfc5740df8f743367015d14ce/setup.py", line 4, in <module>
#0 35.30           setup(use_scm_version=True)
#0 35.30         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
#0 35.30           _install_setup_requires(attrs)
#0 35.30         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
#0 35.30           dist.fetch_build_eggs(dist.setup_requires)
#0 35.30         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
#0 35.30           resolved_dists = pkg_resources.working_set.resolve(
#0 35.30         File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
#0 35.30           raise VersionConflict(dist, req).with_context(dependent_req)
#0 35.30       pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-y1ihcgko/measurement_bfb6e0bbfc5740df8f743367015d14ce/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})
#0 35.30       [end of output]
#0 35.30
#0 35.30   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 35.30 error: metadata-generation-failed
#0 35.30
#0 35.30 × Encountered error while generating package metadata.
#0 35.30 ╰─> See above for output.
#0 35.30
#0 35.30 note: This is an issue with the package mentioned above, not pip.
#0 35.30 hint: See above for details.```

**Comment by marek-bohuncak** [comment]
I have the same problem, saleor-dashboard docker build fails with the error mentioned by @jhsenjaliya above

**Comment by jhsenjaliya** [comment]
here is a solution for timebeing until the `saleor-platform` master gets fixed.

- checkout latest release tag for both `saleor` and `saleor-dashboard` to 3.10.0
```cd saleor
git checkout 3.10.0
cd saleor-dashboard
git checkout 3.10.0
```

follow the "installation with docker guide. thought the last command throw me following error
```
 docker-compose run --rm api python3 manage.py createsuperuser
```

Error:

```
RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

so just pass the --createssuperuser flag while populating the db
```
docker-compose run --rm api python3 manage.py populatedb --createsuperuser
```

and then 

`docker-compose up` worked !

**Comment by patrys** [comment]
The repository now uses official Docker images so the build step is no longer necessary.
