### ISSUE TITLE
Apollo fails making connection to 127.0.0.1:8000 (Storefront fails to start)

### ISSUE THREAD

**Issue by gorjan-mishevski** [saleor/saleor-platform#94]
I just started the saleor platform without changing anything and was unable to run the storefront container.
It seems Apollo is unable to connect to the graphql instance.

Opening the graphql editor works like a charm. ie: localhost:8000.
The problem is when the storefront tries to connect to the graphql instance.
Dashboard works, saleor core works. I am on version 3.
Ran the command to update to the latest version for saleor platform. 

Storefront is on commit: 4ff54d5598a85f49d9a2ec03196d874eb3f62e20

macOS big sur

I think this is a bug.

EDIT: Tried running on master branch, fails to start.

```
storefront_1  | { Error: Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
storefront_1  |     at new ApolloError (/app/node_modules/apollo-client/bundle.umd.js:92:26)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1588:34
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2008:15
storefront_1  |     at Set.forEach (<anonymous>)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2006:26
storefront_1  |     at Map.forEach (<anonymous>)
storefront_1  |     at QueryManager.broadcastQueries (/app/node_modules/apollo-client/bundle.umd.js:2004:20)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1483:29
storefront_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
storefront_1  |   graphQLErrors: [],
storefront_1  |   networkError:
storefront_1  |    { FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
storefront_1  |        at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
storefront_1  |        at ClientRequest.emit (events.js:198:13)
storefront_1  |        at Socket.socketErrorListener (_http_client.js:401:9)
storefront_1  |        at Socket.emit (events.js:198:13)
storefront_1  |        at emitErrorNT (internal/streams/destroy.js:91:8)
storefront_1  |        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
storefront_1  |        at process._tickCallback (internal/process/next_tick.js:63:19)
storefront_1  |      message:
storefront_1  |       'request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
storefront_1  |      type: 'system',
storefront_1  |      errno: 'ECONNREFUSED',
storefront_1  |      code: 'ECONNREFUSED' },
storefront_1  |   message:
storefront_1  |    'Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
storefront_1  |   extraInfo: undefined }
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events
storefront_1  | (node:27) UnhandledPromiseRejectionWarning: Error: Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
storefront_1  |     at new ApolloError (/app/node_modules/apollo-client/bundle.umd.js:92:26)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1588:34
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2008:15
storefront_1  |     at Set.forEach (<anonymous>)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2006:26
storefront_1  |     at Map.forEach (<anonymous>)
storefront_1  |     at QueryManager.broadcastQueries (/app/node_modules/apollo-client/bundle.umd.js:2004:20)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1483:29
storefront_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
storefront_1  | (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 305)
```

**Comment by prashantidealittechno** [comment]
I am facing issue too with the frontend, it is not working for me too.

**Comment by SwitchedToGitlab** [comment]
Where are you configuring the NEXT_PUBLIC_API_URI value?

**Comment by healthyl** [comment]
Hi guys, im experiencing the same issue. Any updates on this one? Also tried to set the --hostname param to --host as i saw somewhere as a suggestion to fix this but it didnt do it for me.

**Comment by lkostrowski** [comment]
Hi, storefront has been rebuilt a lot, please try updating it

**Comment by AlexisHeap** [comment]
Hello @lkostrowski updating it also fix the issue of saleor-platform? or is there another solution? I ran this with docker compose up ? I dockerized this repository (saleor-platform) yesterday in a new VM.

all containers are running:

![image](https://user-images.githubusercontent.com/119627818/207670048-8dc5dcb1-e76d-4007-a562-416d3156cad7.png)

this is the error output:

![image](https://user-images.githubusercontent.com/119627818/207670342-4bf1e476-927d-4c1a-a214-4a779bb1d9f8.png)

Thank you in advance!

**Comment by lkostrowski** [comment]
Hi @AlexisHeap , have you tried running fresh `git clone` first?

**Comment by AlexisHeap** [comment]
Ok perfect, It's working now, thank you! @lkostrowski

**Comment by FouadDakhel96** [comment]
I tried to do git clone again and still the same error "ApolloError"
<img width="1402" alt="Screen Shot 2022-12-28 at 4 35 40 PM" src="https://user-images.githubusercontent.com/32363975/209820488-ff70eb67-a93b-42ba-9cce-d5c08f2f60c3.png">

@lkostrowski

**Comment by lkostrowski** [comment]
@saleor/storefront-checkout can you check this one?

**Comment by patrys** [comment]
Storefront is no longer part of the platform, so I'm closing this. Please report related problems in the project's repository.
